#ifndef V8_BUILTINS_GENERATED_BYTECODES_BUILTINS_LIST_H_
#define V8_BUILTINS_GENERATED_BYTECODES_BUILTINS_LIST_H_

// Handler counts for builtins.h
static constexpr int kNumberOfBytecodeHandlers = 211;
static constexpr int kNumberOfWideBytecodeHandlers = 422;

#define BUILTIN_LIST_BYTECODE_HANDLERS(V, V_WIDE) \
  V(Star15Handler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kStar15) \
  V_WIDE(Star15HandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kStar15) \
  V_WIDE(Star15HandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kStar15) \
  V(Star14Handler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kStar14) \
  V_WIDE(Star14HandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kStar14) \
  V_WIDE(Star14HandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kStar14) \
  V(Star13Handler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kStar13) \
  V_WIDE(Star13HandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kStar13) \
  V_WIDE(Star13HandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kStar13) \
  V(Star12Handler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kStar12) \
  V_WIDE(Star12HandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kStar12) \
  V_WIDE(Star12HandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kStar12) \
  V(Star11Handler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kStar11) \
  V_WIDE(Star11HandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kStar11) \
  V_WIDE(Star11HandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kStar11) \
  V(Star10Handler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kStar10) \
  V_WIDE(Star10HandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kStar10) \
  V_WIDE(Star10HandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kStar10) \
  V(Star9Handler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kStar9) \
  V_WIDE(Star9HandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kStar9) \
  V_WIDE(Star9HandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kStar9) \
  V(Star8Handler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kStar8) \
  V_WIDE(Star8HandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kStar8) \
  V_WIDE(Star8HandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kStar8) \
  V(Star7Handler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kStar7) \
  V_WIDE(Star7HandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kStar7) \
  V_WIDE(Star7HandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kStar7) \
  V(Star6Handler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kStar6) \
  V_WIDE(Star6HandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kStar6) \
  V_WIDE(Star6HandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kStar6) \
  V(Star5Handler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kStar5) \
  V_WIDE(Star5HandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kStar5) \
  V_WIDE(Star5HandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kStar5) \
  V(Star4Handler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kStar4) \
  V_WIDE(Star4HandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kStar4) \
  V_WIDE(Star4HandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kStar4) \
  V(Star3Handler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kStar3) \
  V_WIDE(Star3HandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kStar3) \
  V_WIDE(Star3HandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kStar3) \
  V(Star2Handler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kStar2) \
  V_WIDE(Star2HandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kStar2) \
  V_WIDE(Star2HandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kStar2) \
  V(Star1Handler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kStar1) \
  V_WIDE(Star1HandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kStar1) \
  V_WIDE(Star1HandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kStar1) \
  V(Star0Handler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kStar0) \
  V_WIDE(Star0HandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kStar0) \
  V_WIDE(Star0HandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kStar0) \
  V(CallPropertyHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kCallProperty) \
  V_WIDE(CallPropertyHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kCallProperty) \
  V_WIDE(CallPropertyHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kCallProperty) \
  V(CallProperty0Handler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kCallProperty0) \
  V_WIDE(CallProperty0HandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kCallProperty0) \
  V_WIDE(CallProperty0HandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kCallProperty0) \
  V(CallProperty1Handler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kCallProperty1) \
  V_WIDE(CallProperty1HandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kCallProperty1) \
  V_WIDE(CallProperty1HandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kCallProperty1) \
  V(CallProperty2Handler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kCallProperty2) \
  V_WIDE(CallProperty2HandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kCallProperty2) \
  V_WIDE(CallProperty2HandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kCallProperty2) \
  V(WideHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kWide) \
  V_WIDE(WideHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kWide) \
  V_WIDE(WideHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kWide) \
  V(ExtraWideHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kExtraWide) \
  V_WIDE(ExtraWideHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kExtraWide) \
  V_WIDE(ExtraWideHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kExtraWide) \
  V(DebugBreakWideHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kDebugBreakWide) \
  V_WIDE(DebugBreakWideHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kDebugBreakWide) \
  V_WIDE(DebugBreakWideHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kDebugBreakWide) \
  V(DebugBreakExtraWideHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kDebugBreakExtraWide) \
  V_WIDE(DebugBreakExtraWideHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kDebugBreakExtraWide) \
  V_WIDE(DebugBreakExtraWideHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kDebugBreakExtraWide) \
  V(DebugBreak0Handler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kDebugBreak0) \
  V_WIDE(DebugBreak0HandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kDebugBreak0) \
  V_WIDE(DebugBreak0HandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kDebugBreak0) \
  V(DebugBreak1Handler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kDebugBreak1) \
  V_WIDE(DebugBreak1HandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kDebugBreak1) \
  V_WIDE(DebugBreak1HandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kDebugBreak1) \
  V(DebugBreak2Handler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kDebugBreak2) \
  V_WIDE(DebugBreak2HandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kDebugBreak2) \
  V_WIDE(DebugBreak2HandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kDebugBreak2) \
  V(DebugBreak3Handler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kDebugBreak3) \
  V_WIDE(DebugBreak3HandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kDebugBreak3) \
  V_WIDE(DebugBreak3HandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kDebugBreak3) \
  V(DebugBreak4Handler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kDebugBreak4) \
  V_WIDE(DebugBreak4HandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kDebugBreak4) \
  V_WIDE(DebugBreak4HandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kDebugBreak4) \
  V(DebugBreak5Handler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kDebugBreak5) \
  V_WIDE(DebugBreak5HandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kDebugBreak5) \
  V_WIDE(DebugBreak5HandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kDebugBreak5) \
  V(DebugBreak6Handler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kDebugBreak6) \
  V_WIDE(DebugBreak6HandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kDebugBreak6) \
  V_WIDE(DebugBreak6HandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kDebugBreak6) \
  V(LdarHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kLdar) \
  V_WIDE(LdarHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kLdar) \
  V_WIDE(LdarHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kLdar) \
  V(LdaZeroHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kLdaZero) \
  V_WIDE(LdaZeroHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kLdaZero) \
  V_WIDE(LdaZeroHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kLdaZero) \
  V(LdaSmiHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kLdaSmi) \
  V_WIDE(LdaSmiHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kLdaSmi) \
  V_WIDE(LdaSmiHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kLdaSmi) \
  V(LdaUndefinedHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kLdaUndefined) \
  V_WIDE(LdaUndefinedHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kLdaUndefined) \
  V_WIDE(LdaUndefinedHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kLdaUndefined) \
  V(LdaNullHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kLdaNull) \
  V_WIDE(LdaNullHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kLdaNull) \
  V_WIDE(LdaNullHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kLdaNull) \
  V(LdaTheHoleHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kLdaTheHole) \
  V_WIDE(LdaTheHoleHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kLdaTheHole) \
  V_WIDE(LdaTheHoleHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kLdaTheHole) \
  V(LdaTrueHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kLdaTrue) \
  V_WIDE(LdaTrueHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kLdaTrue) \
  V_WIDE(LdaTrueHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kLdaTrue) \
  V(LdaFalseHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kLdaFalse) \
  V_WIDE(LdaFalseHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kLdaFalse) \
  V_WIDE(LdaFalseHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kLdaFalse) \
  V(LdaConstantHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kLdaConstant) \
  V_WIDE(LdaConstantHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kLdaConstant) \
  V_WIDE(LdaConstantHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kLdaConstant) \
  V(LdaContextSlotNoCellHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kLdaContextSlotNoCell) \
  V_WIDE(LdaContextSlotNoCellHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kLdaContextSlotNoCell) \
  V_WIDE(LdaContextSlotNoCellHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kLdaContextSlotNoCell) \
  V(LdaContextSlotHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kLdaContextSlot) \
  V_WIDE(LdaContextSlotHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kLdaContextSlot) \
  V_WIDE(LdaContextSlotHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kLdaContextSlot) \
  V(LdaImmutableContextSlotHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kLdaImmutableContextSlot) \
  V_WIDE(LdaImmutableContextSlotHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kLdaImmutableContextSlot) \
  V_WIDE(LdaImmutableContextSlotHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kLdaImmutableContextSlot) \
  V(LdaCurrentContextSlotNoCellHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kLdaCurrentContextSlotNoCell) \
  V_WIDE(LdaCurrentContextSlotNoCellHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kLdaCurrentContextSlotNoCell) \
  V_WIDE(LdaCurrentContextSlotNoCellHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kLdaCurrentContextSlotNoCell) \
  V(LdaCurrentContextSlotHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kLdaCurrentContextSlot) \
  V_WIDE(LdaCurrentContextSlotHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kLdaCurrentContextSlot) \
  V_WIDE(LdaCurrentContextSlotHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kLdaCurrentContextSlot) \
  V(LdaImmutableCurrentContextSlotHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kLdaImmutableCurrentContextSlot) \
  V_WIDE(LdaImmutableCurrentContextSlotHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kLdaImmutableCurrentContextSlot) \
  V_WIDE(LdaImmutableCurrentContextSlotHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kLdaImmutableCurrentContextSlot) \
  V(StarHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kStar) \
  V_WIDE(StarHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kStar) \
  V_WIDE(StarHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kStar) \
  V(MovHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kMov) \
  V_WIDE(MovHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kMov) \
  V_WIDE(MovHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kMov) \
  V(PushContextHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kPushContext) \
  V_WIDE(PushContextHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kPushContext) \
  V_WIDE(PushContextHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kPushContext) \
  V(PopContextHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kPopContext) \
  V_WIDE(PopContextHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kPopContext) \
  V_WIDE(PopContextHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kPopContext) \
  V(TestReferenceEqualHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kTestReferenceEqual) \
  V_WIDE(TestReferenceEqualHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kTestReferenceEqual) \
  V_WIDE(TestReferenceEqualHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kTestReferenceEqual) \
  V(TestUndetectableHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kTestUndetectable) \
  V_WIDE(TestUndetectableHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kTestUndetectable) \
  V_WIDE(TestUndetectableHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kTestUndetectable) \
  V(TestNullHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kTestNull) \
  V_WIDE(TestNullHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kTestNull) \
  V_WIDE(TestNullHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kTestNull) \
  V(TestUndefinedHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kTestUndefined) \
  V_WIDE(TestUndefinedHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kTestUndefined) \
  V_WIDE(TestUndefinedHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kTestUndefined) \
  V(TestTypeOfHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kTestTypeOf) \
  V_WIDE(TestTypeOfHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kTestTypeOf) \
  V_WIDE(TestTypeOfHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kTestTypeOf) \
  V(LdaGlobalHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kLdaGlobal) \
  V_WIDE(LdaGlobalHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kLdaGlobal) \
  V_WIDE(LdaGlobalHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kLdaGlobal) \
  V(LdaGlobalInsideTypeofHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kLdaGlobalInsideTypeof) \
  V_WIDE(LdaGlobalInsideTypeofHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kLdaGlobalInsideTypeof) \
  V_WIDE(LdaGlobalInsideTypeofHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kLdaGlobalInsideTypeof) \
  V(StaGlobalHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kStaGlobal) \
  V_WIDE(StaGlobalHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kStaGlobal) \
  V_WIDE(StaGlobalHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kStaGlobal) \
  V(StaContextSlotNoCellHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kStaContextSlotNoCell) \
  V_WIDE(StaContextSlotNoCellHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kStaContextSlotNoCell) \
  V_WIDE(StaContextSlotNoCellHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kStaContextSlotNoCell) \
  V(StaCurrentContextSlotNoCellHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kStaCurrentContextSlotNoCell) \
  V_WIDE(StaCurrentContextSlotNoCellHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kStaCurrentContextSlotNoCell) \
  V_WIDE(StaCurrentContextSlotNoCellHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kStaCurrentContextSlotNoCell) \
  V(StaContextSlotHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kStaContextSlot) \
  V_WIDE(StaContextSlotHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kStaContextSlot) \
  V_WIDE(StaContextSlotHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kStaContextSlot) \
  V(StaCurrentContextSlotHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kStaCurrentContextSlot) \
  V_WIDE(StaCurrentContextSlotHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kStaCurrentContextSlot) \
  V_WIDE(StaCurrentContextSlotHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kStaCurrentContextSlot) \
  V(LdaLookupSlotHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kLdaLookupSlot) \
  V_WIDE(LdaLookupSlotHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kLdaLookupSlot) \
  V_WIDE(LdaLookupSlotHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kLdaLookupSlot) \
  V(LdaLookupContextSlotNoCellHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kLdaLookupContextSlotNoCell) \
  V_WIDE(LdaLookupContextSlotNoCellHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kLdaLookupContextSlotNoCell) \
  V_WIDE(LdaLookupContextSlotNoCellHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kLdaLookupContextSlotNoCell) \
  V(LdaLookupContextSlotHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kLdaLookupContextSlot) \
  V_WIDE(LdaLookupContextSlotHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kLdaLookupContextSlot) \
  V_WIDE(LdaLookupContextSlotHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kLdaLookupContextSlot) \
  V(LdaLookupGlobalSlotHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kLdaLookupGlobalSlot) \
  V_WIDE(LdaLookupGlobalSlotHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kLdaLookupGlobalSlot) \
  V_WIDE(LdaLookupGlobalSlotHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kLdaLookupGlobalSlot) \
  V(LdaLookupSlotInsideTypeofHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kLdaLookupSlotInsideTypeof) \
  V_WIDE(LdaLookupSlotInsideTypeofHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kLdaLookupSlotInsideTypeof) \
  V_WIDE(LdaLookupSlotInsideTypeofHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kLdaLookupSlotInsideTypeof) \
  V(LdaLookupContextSlotInsideTypeofHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kLdaLookupContextSlotInsideTypeof) \
  V_WIDE(LdaLookupContextSlotInsideTypeofHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kLdaLookupContextSlotInsideTypeof) \
  V_WIDE(LdaLookupContextSlotInsideTypeofHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kLdaLookupContextSlotInsideTypeof) \
  V(LdaLookupGlobalSlotInsideTypeofHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kLdaLookupGlobalSlotInsideTypeof) \
  V_WIDE(LdaLookupGlobalSlotInsideTypeofHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kLdaLookupGlobalSlotInsideTypeof) \
  V_WIDE(LdaLookupGlobalSlotInsideTypeofHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kLdaLookupGlobalSlotInsideTypeof) \
  V(StaLookupSlotHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kStaLookupSlot) \
  V_WIDE(StaLookupSlotHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kStaLookupSlot) \
  V_WIDE(StaLookupSlotHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kStaLookupSlot) \
  V(GetNamedPropertyHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kGetNamedProperty) \
  V_WIDE(GetNamedPropertyHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kGetNamedProperty) \
  V_WIDE(GetNamedPropertyHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kGetNamedProperty) \
  V(GetNamedPropertyFromSuperHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kGetNamedPropertyFromSuper) \
  V_WIDE(GetNamedPropertyFromSuperHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kGetNamedPropertyFromSuper) \
  V_WIDE(GetNamedPropertyFromSuperHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kGetNamedPropertyFromSuper) \
  V(GetKeyedPropertyHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kGetKeyedProperty) \
  V_WIDE(GetKeyedPropertyHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kGetKeyedProperty) \
  V_WIDE(GetKeyedPropertyHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kGetKeyedProperty) \
  V(GetEnumeratedKeyedPropertyHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kGetEnumeratedKeyedProperty) \
  V_WIDE(GetEnumeratedKeyedPropertyHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kGetEnumeratedKeyedProperty) \
  V_WIDE(GetEnumeratedKeyedPropertyHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kGetEnumeratedKeyedProperty) \
  V(GetPrivateFieldHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kGetPrivateField) \
  V_WIDE(GetPrivateFieldHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kGetPrivateField) \
  V_WIDE(GetPrivateFieldHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kGetPrivateField) \
  V(LdaModuleVariableHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kLdaModuleVariable) \
  V_WIDE(LdaModuleVariableHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kLdaModuleVariable) \
  V_WIDE(LdaModuleVariableHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kLdaModuleVariable) \
  V(StaModuleVariableHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kStaModuleVariable) \
  V_WIDE(StaModuleVariableHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kStaModuleVariable) \
  V_WIDE(StaModuleVariableHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kStaModuleVariable) \
  V(SetNamedPropertyHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kSetNamedProperty) \
  V_WIDE(SetNamedPropertyHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kSetNamedProperty) \
  V_WIDE(SetNamedPropertyHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kSetNamedProperty) \
  V(DefineNamedOwnPropertyHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kDefineNamedOwnProperty) \
  V_WIDE(DefineNamedOwnPropertyHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kDefineNamedOwnProperty) \
  V_WIDE(DefineNamedOwnPropertyHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kDefineNamedOwnProperty) \
  V(SetKeyedPropertyHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kSetKeyedProperty) \
  V_WIDE(SetKeyedPropertyHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kSetKeyedProperty) \
  V_WIDE(SetKeyedPropertyHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kSetKeyedProperty) \
  V(DefineKeyedOwnPropertyHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kDefineKeyedOwnProperty) \
  V_WIDE(DefineKeyedOwnPropertyHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kDefineKeyedOwnProperty) \
  V_WIDE(DefineKeyedOwnPropertyHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kDefineKeyedOwnProperty) \
  V(StaInArrayLiteralHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kStaInArrayLiteral) \
  V_WIDE(StaInArrayLiteralHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kStaInArrayLiteral) \
  V_WIDE(StaInArrayLiteralHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kStaInArrayLiteral) \
  V(DefineKeyedOwnPropertyInLiteralHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kDefineKeyedOwnPropertyInLiteral) \
  V_WIDE(DefineKeyedOwnPropertyInLiteralHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kDefineKeyedOwnPropertyInLiteral) \
  V_WIDE(DefineKeyedOwnPropertyInLiteralHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kDefineKeyedOwnPropertyInLiteral) \
  V(SetPrototypePropertiesHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kSetPrototypeProperties) \
  V_WIDE(SetPrototypePropertiesHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kSetPrototypeProperties) \
  V_WIDE(SetPrototypePropertiesHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kSetPrototypeProperties) \
  V(SetPrivateFieldHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kSetPrivateField) \
  V_WIDE(SetPrivateFieldHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kSetPrivateField) \
  V_WIDE(SetPrivateFieldHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kSetPrivateField) \
  V(AddHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kAdd) \
  V_WIDE(AddHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kAdd) \
  V_WIDE(AddHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kAdd) \
  V(SubHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kSub) \
  V_WIDE(SubHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kSub) \
  V_WIDE(SubHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kSub) \
  V(MulHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kMul) \
  V_WIDE(MulHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kMul) \
  V_WIDE(MulHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kMul) \
  V(DivHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kDiv) \
  V_WIDE(DivHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kDiv) \
  V_WIDE(DivHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kDiv) \
  V(ModHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kMod) \
  V_WIDE(ModHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kMod) \
  V_WIDE(ModHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kMod) \
  V(ExpHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kExp) \
  V_WIDE(ExpHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kExp) \
  V_WIDE(ExpHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kExp) \
  V(BitwiseOrHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kBitwiseOr) \
  V_WIDE(BitwiseOrHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kBitwiseOr) \
  V_WIDE(BitwiseOrHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kBitwiseOr) \
  V(BitwiseXorHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kBitwiseXor) \
  V_WIDE(BitwiseXorHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kBitwiseXor) \
  V_WIDE(BitwiseXorHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kBitwiseXor) \
  V(BitwiseAndHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kBitwiseAnd) \
  V_WIDE(BitwiseAndHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kBitwiseAnd) \
  V_WIDE(BitwiseAndHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kBitwiseAnd) \
  V(ShiftLeftHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kShiftLeft) \
  V_WIDE(ShiftLeftHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kShiftLeft) \
  V_WIDE(ShiftLeftHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kShiftLeft) \
  V(ShiftRightHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kShiftRight) \
  V_WIDE(ShiftRightHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kShiftRight) \
  V_WIDE(ShiftRightHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kShiftRight) \
  V(ShiftRightLogicalHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kShiftRightLogical) \
  V_WIDE(ShiftRightLogicalHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kShiftRightLogical) \
  V_WIDE(ShiftRightLogicalHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kShiftRightLogical) \
  V(AddSmiHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kAddSmi) \
  V_WIDE(AddSmiHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kAddSmi) \
  V_WIDE(AddSmiHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kAddSmi) \
  V(SubSmiHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kSubSmi) \
  V_WIDE(SubSmiHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kSubSmi) \
  V_WIDE(SubSmiHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kSubSmi) \
  V(MulSmiHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kMulSmi) \
  V_WIDE(MulSmiHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kMulSmi) \
  V_WIDE(MulSmiHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kMulSmi) \
  V(DivSmiHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kDivSmi) \
  V_WIDE(DivSmiHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kDivSmi) \
  V_WIDE(DivSmiHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kDivSmi) \
  V(ModSmiHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kModSmi) \
  V_WIDE(ModSmiHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kModSmi) \
  V_WIDE(ModSmiHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kModSmi) \
  V(ExpSmiHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kExpSmi) \
  V_WIDE(ExpSmiHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kExpSmi) \
  V_WIDE(ExpSmiHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kExpSmi) \
  V(BitwiseOrSmiHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kBitwiseOrSmi) \
  V_WIDE(BitwiseOrSmiHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kBitwiseOrSmi) \
  V_WIDE(BitwiseOrSmiHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kBitwiseOrSmi) \
  V(BitwiseXorSmiHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kBitwiseXorSmi) \
  V_WIDE(BitwiseXorSmiHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kBitwiseXorSmi) \
  V_WIDE(BitwiseXorSmiHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kBitwiseXorSmi) \
  V(BitwiseAndSmiHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kBitwiseAndSmi) \
  V_WIDE(BitwiseAndSmiHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kBitwiseAndSmi) \
  V_WIDE(BitwiseAndSmiHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kBitwiseAndSmi) \
  V(ShiftLeftSmiHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kShiftLeftSmi) \
  V_WIDE(ShiftLeftSmiHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kShiftLeftSmi) \
  V_WIDE(ShiftLeftSmiHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kShiftLeftSmi) \
  V(ShiftRightSmiHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kShiftRightSmi) \
  V_WIDE(ShiftRightSmiHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kShiftRightSmi) \
  V_WIDE(ShiftRightSmiHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kShiftRightSmi) \
  V(ShiftRightLogicalSmiHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kShiftRightLogicalSmi) \
  V_WIDE(ShiftRightLogicalSmiHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kShiftRightLogicalSmi) \
  V_WIDE(ShiftRightLogicalSmiHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kShiftRightLogicalSmi) \
  V(IncHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kInc) \
  V_WIDE(IncHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kInc) \
  V_WIDE(IncHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kInc) \
  V(DecHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kDec) \
  V_WIDE(DecHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kDec) \
  V_WIDE(DecHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kDec) \
  V(NegateHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kNegate) \
  V_WIDE(NegateHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kNegate) \
  V_WIDE(NegateHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kNegate) \
  V(ToBooleanLogicalNotHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kToBooleanLogicalNot) \
  V_WIDE(ToBooleanLogicalNotHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kToBooleanLogicalNot) \
  V_WIDE(ToBooleanLogicalNotHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kToBooleanLogicalNot) \
  V(LogicalNotHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kLogicalNot) \
  V_WIDE(LogicalNotHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kLogicalNot) \
  V_WIDE(LogicalNotHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kLogicalNot) \
  V(TypeOfHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kTypeOf) \
  V_WIDE(TypeOfHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kTypeOf) \
  V_WIDE(TypeOfHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kTypeOf) \
  V(DeletePropertyStrictHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kDeletePropertyStrict) \
  V_WIDE(DeletePropertyStrictHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kDeletePropertyStrict) \
  V_WIDE(DeletePropertyStrictHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kDeletePropertyStrict) \
  V(DeletePropertySloppyHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kDeletePropertySloppy) \
  V_WIDE(DeletePropertySloppyHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kDeletePropertySloppy) \
  V_WIDE(DeletePropertySloppyHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kDeletePropertySloppy) \
  V(GetSuperConstructorHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kGetSuperConstructor) \
  V_WIDE(GetSuperConstructorHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kGetSuperConstructor) \
  V_WIDE(GetSuperConstructorHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kGetSuperConstructor) \
  V(FindNonDefaultConstructorOrConstructHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kFindNonDefaultConstructorOrConstruct) \
  V_WIDE(FindNonDefaultConstructorOrConstructHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kFindNonDefaultConstructorOrConstruct) \
  V_WIDE(FindNonDefaultConstructorOrConstructHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kFindNonDefaultConstructorOrConstruct) \
  V(CallAnyReceiverHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kCallAnyReceiver) \
  V_WIDE(CallAnyReceiverHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kCallAnyReceiver) \
  V_WIDE(CallAnyReceiverHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kCallAnyReceiver) \
  V(CallUndefinedReceiverHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kCallUndefinedReceiver) \
  V_WIDE(CallUndefinedReceiverHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kCallUndefinedReceiver) \
  V_WIDE(CallUndefinedReceiverHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kCallUndefinedReceiver) \
  V(CallUndefinedReceiver0Handler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kCallUndefinedReceiver0) \
  V_WIDE(CallUndefinedReceiver0HandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kCallUndefinedReceiver0) \
  V_WIDE(CallUndefinedReceiver0HandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kCallUndefinedReceiver0) \
  V(CallUndefinedReceiver1Handler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kCallUndefinedReceiver1) \
  V_WIDE(CallUndefinedReceiver1HandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kCallUndefinedReceiver1) \
  V_WIDE(CallUndefinedReceiver1HandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kCallUndefinedReceiver1) \
  V(CallUndefinedReceiver2Handler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kCallUndefinedReceiver2) \
  V_WIDE(CallUndefinedReceiver2HandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kCallUndefinedReceiver2) \
  V_WIDE(CallUndefinedReceiver2HandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kCallUndefinedReceiver2) \
  V(CallWithSpreadHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kCallWithSpread) \
  V_WIDE(CallWithSpreadHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kCallWithSpread) \
  V_WIDE(CallWithSpreadHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kCallWithSpread) \
  V(CallRuntimeHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kCallRuntime) \
  V_WIDE(CallRuntimeHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kCallRuntime) \
  V_WIDE(CallRuntimeHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kCallRuntime) \
  V(CallRuntimeForPairHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kCallRuntimeForPair) \
  V_WIDE(CallRuntimeForPairHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kCallRuntimeForPair) \
  V_WIDE(CallRuntimeForPairHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kCallRuntimeForPair) \
  V(CallJSRuntimeHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kCallJSRuntime) \
  V_WIDE(CallJSRuntimeHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kCallJSRuntime) \
  V_WIDE(CallJSRuntimeHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kCallJSRuntime) \
  V(InvokeIntrinsicHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kInvokeIntrinsic) \
  V_WIDE(InvokeIntrinsicHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kInvokeIntrinsic) \
  V_WIDE(InvokeIntrinsicHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kInvokeIntrinsic) \
  V(ConstructHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kConstruct) \
  V_WIDE(ConstructHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kConstruct) \
  V_WIDE(ConstructHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kConstruct) \
  V(ConstructWithSpreadHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kConstructWithSpread) \
  V_WIDE(ConstructWithSpreadHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kConstructWithSpread) \
  V_WIDE(ConstructWithSpreadHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kConstructWithSpread) \
  V(ConstructForwardAllArgsHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kConstructForwardAllArgs) \
  V_WIDE(ConstructForwardAllArgsHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kConstructForwardAllArgs) \
  V_WIDE(ConstructForwardAllArgsHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kConstructForwardAllArgs) \
  V(TestEqualHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kTestEqual) \
  V_WIDE(TestEqualHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kTestEqual) \
  V_WIDE(TestEqualHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kTestEqual) \
  V(TestEqualStrictHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kTestEqualStrict) \
  V_WIDE(TestEqualStrictHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kTestEqualStrict) \
  V_WIDE(TestEqualStrictHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kTestEqualStrict) \
  V(TestLessThanHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kTestLessThan) \
  V_WIDE(TestLessThanHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kTestLessThan) \
  V_WIDE(TestLessThanHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kTestLessThan) \
  V(TestGreaterThanHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kTestGreaterThan) \
  V_WIDE(TestGreaterThanHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kTestGreaterThan) \
  V_WIDE(TestGreaterThanHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kTestGreaterThan) \
  V(TestLessThanOrEqualHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kTestLessThanOrEqual) \
  V_WIDE(TestLessThanOrEqualHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kTestLessThanOrEqual) \
  V_WIDE(TestLessThanOrEqualHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kTestLessThanOrEqual) \
  V(TestGreaterThanOrEqualHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kTestGreaterThanOrEqual) \
  V_WIDE(TestGreaterThanOrEqualHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kTestGreaterThanOrEqual) \
  V_WIDE(TestGreaterThanOrEqualHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kTestGreaterThanOrEqual) \
  V(TestInstanceOfHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kTestInstanceOf) \
  V_WIDE(TestInstanceOfHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kTestInstanceOf) \
  V_WIDE(TestInstanceOfHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kTestInstanceOf) \
  V(TestInHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kTestIn) \
  V_WIDE(TestInHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kTestIn) \
  V_WIDE(TestInHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kTestIn) \
  V(ToNameHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kToName) \
  V_WIDE(ToNameHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kToName) \
  V_WIDE(ToNameHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kToName) \
  V(ToNumberHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kToNumber) \
  V_WIDE(ToNumberHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kToNumber) \
  V_WIDE(ToNumberHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kToNumber) \
  V(ToNumericHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kToNumeric) \
  V_WIDE(ToNumericHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kToNumeric) \
  V_WIDE(ToNumericHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kToNumeric) \
  V(ToObjectHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kToObject) \
  V_WIDE(ToObjectHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kToObject) \
  V_WIDE(ToObjectHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kToObject) \
  V(ToStringHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kToString) \
  V_WIDE(ToStringHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kToString) \
  V_WIDE(ToStringHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kToString) \
  V(ToBooleanHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kToBoolean) \
  V_WIDE(ToBooleanHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kToBoolean) \
  V_WIDE(ToBooleanHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kToBoolean) \
  V(CreateRegExpLiteralHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kCreateRegExpLiteral) \
  V_WIDE(CreateRegExpLiteralHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kCreateRegExpLiteral) \
  V_WIDE(CreateRegExpLiteralHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kCreateRegExpLiteral) \
  V(CreateArrayLiteralHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kCreateArrayLiteral) \
  V_WIDE(CreateArrayLiteralHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kCreateArrayLiteral) \
  V_WIDE(CreateArrayLiteralHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kCreateArrayLiteral) \
  V(CreateArrayFromIterableHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kCreateArrayFromIterable) \
  V_WIDE(CreateArrayFromIterableHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kCreateArrayFromIterable) \
  V_WIDE(CreateArrayFromIterableHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kCreateArrayFromIterable) \
  V(CreateEmptyArrayLiteralHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kCreateEmptyArrayLiteral) \
  V_WIDE(CreateEmptyArrayLiteralHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kCreateEmptyArrayLiteral) \
  V_WIDE(CreateEmptyArrayLiteralHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kCreateEmptyArrayLiteral) \
  V(CreateObjectLiteralHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kCreateObjectLiteral) \
  V_WIDE(CreateObjectLiteralHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kCreateObjectLiteral) \
  V_WIDE(CreateObjectLiteralHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kCreateObjectLiteral) \
  V(CreateEmptyObjectLiteralHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kCreateEmptyObjectLiteral) \
  V_WIDE(CreateEmptyObjectLiteralHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kCreateEmptyObjectLiteral) \
  V_WIDE(CreateEmptyObjectLiteralHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kCreateEmptyObjectLiteral) \
  V(CloneObjectHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kCloneObject) \
  V_WIDE(CloneObjectHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kCloneObject) \
  V_WIDE(CloneObjectHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kCloneObject) \
  V(GetTemplateObjectHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kGetTemplateObject) \
  V_WIDE(GetTemplateObjectHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kGetTemplateObject) \
  V_WIDE(GetTemplateObjectHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kGetTemplateObject) \
  V(CreateClosureHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kCreateClosure) \
  V_WIDE(CreateClosureHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kCreateClosure) \
  V_WIDE(CreateClosureHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kCreateClosure) \
  V(CreateBlockContextHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kCreateBlockContext) \
  V_WIDE(CreateBlockContextHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kCreateBlockContext) \
  V_WIDE(CreateBlockContextHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kCreateBlockContext) \
  V(CreateCatchContextHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kCreateCatchContext) \
  V_WIDE(CreateCatchContextHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kCreateCatchContext) \
  V_WIDE(CreateCatchContextHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kCreateCatchContext) \
  V(CreateFunctionContextHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kCreateFunctionContext) \
  V_WIDE(CreateFunctionContextHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kCreateFunctionContext) \
  V_WIDE(CreateFunctionContextHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kCreateFunctionContext) \
  V(CreateFunctionContextWithCellsHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kCreateFunctionContextWithCells) \
  V_WIDE(CreateFunctionContextWithCellsHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kCreateFunctionContextWithCells) \
  V_WIDE(CreateFunctionContextWithCellsHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kCreateFunctionContextWithCells) \
  V(CreateEvalContextHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kCreateEvalContext) \
  V_WIDE(CreateEvalContextHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kCreateEvalContext) \
  V_WIDE(CreateEvalContextHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kCreateEvalContext) \
  V(CreateWithContextHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kCreateWithContext) \
  V_WIDE(CreateWithContextHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kCreateWithContext) \
  V_WIDE(CreateWithContextHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kCreateWithContext) \
  V(CreateMappedArgumentsHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kCreateMappedArguments) \
  V_WIDE(CreateMappedArgumentsHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kCreateMappedArguments) \
  V_WIDE(CreateMappedArgumentsHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kCreateMappedArguments) \
  V(CreateUnmappedArgumentsHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kCreateUnmappedArguments) \
  V_WIDE(CreateUnmappedArgumentsHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kCreateUnmappedArguments) \
  V_WIDE(CreateUnmappedArgumentsHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kCreateUnmappedArguments) \
  V(CreateRestParameterHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kCreateRestParameter) \
  V_WIDE(CreateRestParameterHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kCreateRestParameter) \
  V_WIDE(CreateRestParameterHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kCreateRestParameter) \
  V(JumpLoopHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kJumpLoop) \
  V_WIDE(JumpLoopHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kJumpLoop) \
  V_WIDE(JumpLoopHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kJumpLoop) \
  V(JumpHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kJump) \
  V_WIDE(JumpHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kJump) \
  V_WIDE(JumpHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kJump) \
  V(JumpConstantHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kJumpConstant) \
  V_WIDE(JumpConstantHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kJumpConstant) \
  V_WIDE(JumpConstantHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kJumpConstant) \
  V(JumpIfNullConstantHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kJumpIfNullConstant) \
  V_WIDE(JumpIfNullConstantHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kJumpIfNullConstant) \
  V_WIDE(JumpIfNullConstantHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kJumpIfNullConstant) \
  V(JumpIfNotNullConstantHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kJumpIfNotNullConstant) \
  V_WIDE(JumpIfNotNullConstantHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kJumpIfNotNullConstant) \
  V_WIDE(JumpIfNotNullConstantHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kJumpIfNotNullConstant) \
  V(JumpIfUndefinedConstantHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kJumpIfUndefinedConstant) \
  V_WIDE(JumpIfUndefinedConstantHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kJumpIfUndefinedConstant) \
  V_WIDE(JumpIfUndefinedConstantHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kJumpIfUndefinedConstant) \
  V(JumpIfNotUndefinedConstantHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kJumpIfNotUndefinedConstant) \
  V_WIDE(JumpIfNotUndefinedConstantHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kJumpIfNotUndefinedConstant) \
  V_WIDE(JumpIfNotUndefinedConstantHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kJumpIfNotUndefinedConstant) \
  V(JumpIfUndefinedOrNullConstantHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kJumpIfUndefinedOrNullConstant) \
  V_WIDE(JumpIfUndefinedOrNullConstantHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kJumpIfUndefinedOrNullConstant) \
  V_WIDE(JumpIfUndefinedOrNullConstantHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kJumpIfUndefinedOrNullConstant) \
  V(JumpIfTrueConstantHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kJumpIfTrueConstant) \
  V_WIDE(JumpIfTrueConstantHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kJumpIfTrueConstant) \
  V_WIDE(JumpIfTrueConstantHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kJumpIfTrueConstant) \
  V(JumpIfFalseConstantHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kJumpIfFalseConstant) \
  V_WIDE(JumpIfFalseConstantHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kJumpIfFalseConstant) \
  V_WIDE(JumpIfFalseConstantHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kJumpIfFalseConstant) \
  V(JumpIfJSReceiverConstantHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kJumpIfJSReceiverConstant) \
  V_WIDE(JumpIfJSReceiverConstantHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kJumpIfJSReceiverConstant) \
  V_WIDE(JumpIfJSReceiverConstantHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kJumpIfJSReceiverConstant) \
  V(JumpIfForInDoneConstantHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kJumpIfForInDoneConstant) \
  V_WIDE(JumpIfForInDoneConstantHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kJumpIfForInDoneConstant) \
  V_WIDE(JumpIfForInDoneConstantHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kJumpIfForInDoneConstant) \
  V(JumpIfToBooleanTrueConstantHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kJumpIfToBooleanTrueConstant) \
  V_WIDE(JumpIfToBooleanTrueConstantHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kJumpIfToBooleanTrueConstant) \
  V_WIDE(JumpIfToBooleanTrueConstantHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kJumpIfToBooleanTrueConstant) \
  V(JumpIfToBooleanFalseConstantHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kJumpIfToBooleanFalseConstant) \
  V_WIDE(JumpIfToBooleanFalseConstantHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kJumpIfToBooleanFalseConstant) \
  V_WIDE(JumpIfToBooleanFalseConstantHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kJumpIfToBooleanFalseConstant) \
  V(JumpIfToBooleanTrueHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kJumpIfToBooleanTrue) \
  V_WIDE(JumpIfToBooleanTrueHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kJumpIfToBooleanTrue) \
  V_WIDE(JumpIfToBooleanTrueHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kJumpIfToBooleanTrue) \
  V(JumpIfToBooleanFalseHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kJumpIfToBooleanFalse) \
  V_WIDE(JumpIfToBooleanFalseHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kJumpIfToBooleanFalse) \
  V_WIDE(JumpIfToBooleanFalseHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kJumpIfToBooleanFalse) \
  V(JumpIfTrueHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kJumpIfTrue) \
  V_WIDE(JumpIfTrueHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kJumpIfTrue) \
  V_WIDE(JumpIfTrueHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kJumpIfTrue) \
  V(JumpIfFalseHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kJumpIfFalse) \
  V_WIDE(JumpIfFalseHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kJumpIfFalse) \
  V_WIDE(JumpIfFalseHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kJumpIfFalse) \
  V(JumpIfNullHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kJumpIfNull) \
  V_WIDE(JumpIfNullHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kJumpIfNull) \
  V_WIDE(JumpIfNullHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kJumpIfNull) \
  V(JumpIfNotNullHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kJumpIfNotNull) \
  V_WIDE(JumpIfNotNullHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kJumpIfNotNull) \
  V_WIDE(JumpIfNotNullHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kJumpIfNotNull) \
  V(JumpIfUndefinedHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kJumpIfUndefined) \
  V_WIDE(JumpIfUndefinedHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kJumpIfUndefined) \
  V_WIDE(JumpIfUndefinedHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kJumpIfUndefined) \
  V(JumpIfNotUndefinedHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kJumpIfNotUndefined) \
  V_WIDE(JumpIfNotUndefinedHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kJumpIfNotUndefined) \
  V_WIDE(JumpIfNotUndefinedHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kJumpIfNotUndefined) \
  V(JumpIfUndefinedOrNullHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kJumpIfUndefinedOrNull) \
  V_WIDE(JumpIfUndefinedOrNullHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kJumpIfUndefinedOrNull) \
  V_WIDE(JumpIfUndefinedOrNullHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kJumpIfUndefinedOrNull) \
  V(JumpIfJSReceiverHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kJumpIfJSReceiver) \
  V_WIDE(JumpIfJSReceiverHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kJumpIfJSReceiver) \
  V_WIDE(JumpIfJSReceiverHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kJumpIfJSReceiver) \
  V(JumpIfForInDoneHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kJumpIfForInDone) \
  V_WIDE(JumpIfForInDoneHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kJumpIfForInDone) \
  V_WIDE(JumpIfForInDoneHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kJumpIfForInDone) \
  V(SwitchOnSmiNoFeedbackHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kSwitchOnSmiNoFeedback) \
  V_WIDE(SwitchOnSmiNoFeedbackHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kSwitchOnSmiNoFeedback) \
  V_WIDE(SwitchOnSmiNoFeedbackHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kSwitchOnSmiNoFeedback) \
  V(ForInEnumerateHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kForInEnumerate) \
  V_WIDE(ForInEnumerateHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kForInEnumerate) \
  V_WIDE(ForInEnumerateHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kForInEnumerate) \
  V(ForInPrepareHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kForInPrepare) \
  V_WIDE(ForInPrepareHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kForInPrepare) \
  V_WIDE(ForInPrepareHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kForInPrepare) \
  V(ForInNextHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kForInNext) \
  V_WIDE(ForInNextHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kForInNext) \
  V_WIDE(ForInNextHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kForInNext) \
  V(ForInStepHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kForInStep) \
  V_WIDE(ForInStepHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kForInStep) \
  V_WIDE(ForInStepHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kForInStep) \
  V(ForOfNextHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kForOfNext) \
  V_WIDE(ForOfNextHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kForOfNext) \
  V_WIDE(ForOfNextHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kForOfNext) \
  V(SetPendingMessageHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kSetPendingMessage) \
  V_WIDE(SetPendingMessageHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kSetPendingMessage) \
  V_WIDE(SetPendingMessageHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kSetPendingMessage) \
  V(ThrowHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kThrow) \
  V_WIDE(ThrowHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kThrow) \
  V_WIDE(ThrowHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kThrow) \
  V(ReThrowHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kReThrow) \
  V_WIDE(ReThrowHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kReThrow) \
  V_WIDE(ReThrowHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kReThrow) \
  V(ReturnHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kReturn) \
  V_WIDE(ReturnHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kReturn) \
  V_WIDE(ReturnHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kReturn) \
  V(ThrowReferenceErrorIfHoleHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kThrowReferenceErrorIfHole) \
  V_WIDE(ThrowReferenceErrorIfHoleHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kThrowReferenceErrorIfHole) \
  V_WIDE(ThrowReferenceErrorIfHoleHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kThrowReferenceErrorIfHole) \
  V(ThrowSuperNotCalledIfHoleHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kThrowSuperNotCalledIfHole) \
  V_WIDE(ThrowSuperNotCalledIfHoleHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kThrowSuperNotCalledIfHole) \
  V_WIDE(ThrowSuperNotCalledIfHoleHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kThrowSuperNotCalledIfHole) \
  V(ThrowSuperAlreadyCalledIfNotHoleHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kThrowSuperAlreadyCalledIfNotHole) \
  V_WIDE(ThrowSuperAlreadyCalledIfNotHoleHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kThrowSuperAlreadyCalledIfNotHole) \
  V_WIDE(ThrowSuperAlreadyCalledIfNotHoleHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kThrowSuperAlreadyCalledIfNotHole) \
  V(ThrowIfNotSuperConstructorHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kThrowIfNotSuperConstructor) \
  V_WIDE(ThrowIfNotSuperConstructorHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kThrowIfNotSuperConstructor) \
  V_WIDE(ThrowIfNotSuperConstructorHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kThrowIfNotSuperConstructor) \
  V(SwitchOnGeneratorStateHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kSwitchOnGeneratorState) \
  V_WIDE(SwitchOnGeneratorStateHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kSwitchOnGeneratorState) \
  V_WIDE(SwitchOnGeneratorStateHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kSwitchOnGeneratorState) \
  V(SuspendGeneratorHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kSuspendGenerator) \
  V_WIDE(SuspendGeneratorHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kSuspendGenerator) \
  V_WIDE(SuspendGeneratorHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kSuspendGenerator) \
  V(ResumeGeneratorHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kResumeGenerator) \
  V_WIDE(ResumeGeneratorHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kResumeGenerator) \
  V_WIDE(ResumeGeneratorHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kResumeGenerator) \
  V(GetIteratorHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kGetIterator) \
  V_WIDE(GetIteratorHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kGetIterator) \
  V_WIDE(GetIteratorHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kGetIterator) \
  V(DebuggerHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kDebugger) \
  V_WIDE(DebuggerHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kDebugger) \
  V_WIDE(DebuggerHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kDebugger) \
  V(IncBlockCounterHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kIncBlockCounter) \
  V_WIDE(IncBlockCounterHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kIncBlockCounter) \
  V_WIDE(IncBlockCounterHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kIncBlockCounter) \
  V(AbortHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kAbort) \
  V_WIDE(AbortHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kAbort) \
  V_WIDE(AbortHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kAbort) \
  V(IllegalHandler, interpreter::OperandScale::kSingle, interpreter::Bytecode::kIllegal) \
  V_WIDE(IllegalHandlerWide, interpreter::OperandScale::kDouble, interpreter::Bytecode::kIllegal) \
  V_WIDE(IllegalHandlerExtraWide, interpreter::OperandScale::kQuadruple, interpreter::Bytecode::kIllegal) \


constexpr int kNumberOfBytecodeHandlers = 211;
constexpr int kNumberOfWideBytecodeHandlers = 211;

constexpr uint8_t kWideBytecodeToBuiltinsMapping[256] = {

  0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,
  16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,
  32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,
  48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,
  64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,
  80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,
  96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,
  112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,
  128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,
  144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,
  160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,
  176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,
  192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,
  208,209,210,211,211,211,211,211,211,211,211,211,211,211,211,211,
  211,211,211,211,211,211,211,211,211,211,211,211,211,211,211,211,
  211,211,211,211,211,211,211,211,211,211,211,211,211,211,211,211
};

constexpr uint8_t kExtraWideBytecodeToBuiltinsMapping[256] = {
  0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,
  16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,
  32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,
  48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,
  64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,
  80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,
  96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,
  112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,
  128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,
  144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,
  160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,
  176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,
  192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,
  208,209,210,211,211,211,211,211,211,211,211,211,211,211,211,211,
  211,211,211,211,211,211,211,211,211,211,211,211,211,211,211,211,
  211,211,211,211,211,211,211,211,211,211,211,211,211,211,211,211
};

constexpr uint8_t kIllegalBytecodeHandlerEncoding = 255;

#endif
