//! Test fixtures for the OCSP module — DER responses generated by
//! `scripts/gen_ocsp_fixture.py`. Only the selftest path uses
//! these; never link from production code.

#![allow(dead_code)]

include!("test_response.rs");
