// CSS property parser stubs for Bat_OS
// Correct signature: returns CSS_INVALID so the CSS parser skips the property gracefully
// The parser then advances to the next semicolon and continues parsing
#include <stdint.h>

// Use opaque pointers — we don't touch any of these structures
typedef struct css_language css_language;
typedef struct parserutils_vector parserutils_vector;
typedef struct css_style css_style;
typedef int css_error;

#define CSS_INVALID 3

#define STUB(name) \
css_error css__parse_##name(css_language *c, \
    const parserutils_vector *vector, int32_t *ctx, css_style *result) { \
    (void)c; (void)vector; (void)ctx; (void)result; \
    return CSS_INVALID; \
}

STUB(align_content)
STUB(align_items)
STUB(align_self)
STUB(background_attachment)
STUB(background_color)
STUB(background_image)
STUB(background_repeat)
STUB(border_bottom)
STUB(border_bottom_color)
STUB(border_bottom_style)
STUB(border_bottom_width)
STUB(border_collapse)
STUB(border_left)
STUB(border_left_color)
STUB(border_left_style)
STUB(border_left_width)
STUB(border_right)
STUB(border_right_color)
STUB(border_right_style)
STUB(border_right_width)
STUB(border_side_color)
STUB(border_side_style)
STUB(border_side_width)
STUB(border_top)
STUB(border_top_color)
STUB(border_top_style)
STUB(border_top_width)
STUB(bottom)
STUB(box_sizing)
STUB(break_after)
STUB(break_before)
STUB(break_inside)
STUB(caption_side)
STUB(clear)
STUB(color)
STUB(column_count)
STUB(column_fill)
STUB(column_gap)
STUB(column_rule_color)
STUB(column_rule_style)
STUB(column_rule_width)
STUB(column_span)
STUB(column_width)
STUB(counter_increment)
STUB(counter_reset)
STUB(cue_after)
STUB(cue_before)
STUB(direction)
STUB(display)
STUB(empty_cells)
STUB(flex_basis)
STUB(flex_direction)
STUB(flex_grow)
STUB(flex_shrink)
STUB(flex_wrap)
STUB(float)
STUB(font_descriptor)
STUB(font_size)
STUB(font_style)
STUB(font_variant)
STUB(height)
STUB(justify_content)
STUB(left)
STUB(letter_spacing)
STUB(line_height)
STUB(list_style_image)
STUB(list_style_position)
STUB(margin_bottom)
STUB(margin_left)
STUB(margin_right)
STUB(margin_top)
STUB(max_height)
STUB(max_width)
STUB(min_height)
STUB(min_width)
STUB(order)
STUB(orphans)
STUB(outline_color)
STUB(outline_style)
STUB(outline_width)
STUB(overflow_x)
STUB(overflow_y)
STUB(padding_bottom)
STUB(padding_left)
STUB(padding_right)
STUB(padding_top)
STUB(page_break_after)
STUB(page_break_before)
STUB(page_break_inside)
STUB(pause_after)
STUB(pause_before)
STUB(pitch)
STUB(pitch_range)
STUB(position)
STUB(richness)
STUB(right)
STUB(speak)
STUB(speak_header)
STUB(speak_numeral)
STUB(speak_punctuation)
STUB(speech_rate)
STUB(stress)
STUB(table_layout)
STUB(text_align)
STUB(text_indent)
STUB(text_transform)
STUB(top)
STUB(unicode_bidi)
STUB(vertical_align)
STUB(visibility)
STUB(volume)
STUB(white_space)
STUB(widows)
STUB(width)
STUB(word_spacing)
STUB(writing_mode)
STUB(z_index)
