#!/usr/bin/env python3
"""
Convert a dtrace trace produced by scripts/macos/trace_mtp_mailbox.d
into a Python m1n1-proxy replay script. The replay calls the same
mailbox primitives against our live M4 to reproduce macOS's exact
boot-up sequence for MTP.

Input: one-line-per-event log, e.g.:
    [10000000] ASCWrapV6::_inbox this=0xffff... msg=[0x0000002200000000 0x0000000000000000]
    [10000050] ASCWrapV6::_triggerFiqNmi this=0xffff...
    [10000120] ASCWrapV6::_outbox this=0xffff... msg=[0x00200001... 0x...]

Output: a self-contained Python module that opens a proxy on
/dev/ttyACM1, DART-maps MTP firmware, and writes/reads the same
sequence. Pipe to a file:
    python3 parse_dtrace_trace.py mtp_init.trace > scripts/hv/replay_mtp_sequence.py
"""
import argparse
import pathlib
import re
import sys
from typing import List, Optional

# --- event regexes ---------------------------------------------------

RE_INBOX = re.compile(
    r"\[(\d+)\]\s+ASCWrapV6::_inbox\s+this=\S+\s+msg=\[0x([0-9a-fA-F]+)\s+0x([0-9a-fA-F]+)\]"
)
RE_OUTBOX = re.compile(
    r"\[(\d+)\]\s+ASCWrapV6::_outbox\s+this=\S+\s+msg=\[0x([0-9a-fA-F]+)\s+0x([0-9a-fA-F]+)\]"
)
RE_DOORBELL = re.compile(
    r"\[(\d+)\]\s+ASCWrapV6::_triggerFiqNmi\s"
)
RE_EXT_DOORBELL = re.compile(
    r"\[(\d+)\]\s+ASCWrapV6::_triggerExtIrqNmi\s"
)
RE_NMI = re.compile(
    r"\[(\d+)\]\s+ASCWrapV6::_generateNMI\s"
)
RE_RUN = re.compile(
    r"\[(\d+)\]\s+ASCWrapV6::_runCPU\s+this=\S+\s+enable=(\d+)"
)
RE_RVBAR = re.compile(
    r"\[(\d+)\]\s+ASCWrapV6::_setIORVBAR\s+this=\S+\s+rvbar=0x([0-9a-fA-F]+)"
)
RE_EN_OUT = re.compile(
    r"\[(\d+)\]\s+ASCWrapV6::_enableOutbox\s+this=\S+\s+enable=(\d+)"
)
RE_EN_IBI = re.compile(
    r"\[(\d+)\]\s+ASCWrapV6::_enableInboxInterrupt\s+this=\S+\s+enable=(\d+)"
)
RE_EN_OBI = re.compile(
    r"\[(\d+)\]\s+ASCWrapV6::_enableOutboxInterrupt\s+this=\S+\s+enable=(\d+)"
)
RE_DIS_INT = re.compile(
    r"\[(\d+)\]\s+ASCWrapV6::_disableAllInterrupts\s"
)
RE_FW_MAP = re.compile(
    r"\[(\d+)\]\s+ASCWrapV6::_mapFirmware\s+this=\S+\s+addr=0x([0-9a-fA-F]+)"
)
RE_START = re.compile(
    r"\[(\d+)\]\s+AppleA7IOP::start\s"
)
RE_STARTCPU = re.compile(
    r"\[(\d+)\]\s+AppleA7IOP::startCPUWithOptions\s"
)


# --- event classes ---------------------------------------------------

class Event:
    def __init__(self, ts: int, kind: str, **kw):
        self.ts = ts
        self.kind = kind
        self.args = kw

    def __repr__(self):
        a = ", ".join(f"{k}={v!r}" for k, v in self.args.items())
        return f"Event({self.ts}, {self.kind!r}, {a})"


def parse_line(line: str) -> Optional[Event]:
    """Return Event for a recognized dtrace line, else None."""
    if m := RE_INBOX.search(line):
        ts, lo, hi = m.groups()
        return Event(int(ts), "inbox", lo=int(lo, 16), hi=int(hi, 16))
    if m := RE_OUTBOX.search(line):
        ts, lo, hi = m.groups()
        return Event(int(ts), "outbox", lo=int(lo, 16), hi=int(hi, 16))
    if m := RE_DOORBELL.search(line):
        return Event(int(m.group(1)), "doorbell")
    if m := RE_EXT_DOORBELL.search(line):
        return Event(int(m.group(1)), "ext_doorbell")
    if m := RE_NMI.search(line):
        return Event(int(m.group(1)), "generateNMI")
    if m := RE_RUN.search(line):
        ts, en = m.groups()
        return Event(int(ts), "runCPU", enable=int(en))
    if m := RE_RVBAR.search(line):
        ts, rvbar = m.groups()
        return Event(int(ts), "setRVBAR", rvbar=int(rvbar, 16))
    if m := RE_EN_OUT.search(line):
        ts, en = m.groups()
        return Event(int(ts), "enableOutbox", enable=int(en))
    if m := RE_EN_IBI.search(line):
        ts, en = m.groups()
        return Event(int(ts), "enableInboxIRQ", enable=int(en))
    if m := RE_EN_OBI.search(line):
        ts, en = m.groups()
        return Event(int(ts), "enableOutboxIRQ", enable=int(en))
    if m := RE_DIS_INT.search(line):
        return Event(int(m.group(1)), "disableAllIRQ")
    if m := RE_FW_MAP.search(line):
        ts, addr = m.groups()
        return Event(int(ts), "mapFirmware", addr=int(addr, 16))
    if m := RE_START.search(line):
        return Event(int(m.group(1)), "start")
    if m := RE_STARTCPU.search(line):
        return Event(int(m.group(1)), "startCPU")
    return None


# --- code generation -------------------------------------------------

REPLAY_HEADER = '''#!/usr/bin/env python3
# AUTO-GENERATED by scripts/macos/parse_dtrace_trace.py
# Replays the MTP mailbox sequence captured live from macOS on our
# m1n1 proxy. Run after chainloading external/m1n1/build/m1n1.macho.
#
# Register layout assumed (confirmed via AppleASCWrapV6 kext disasm):
#   INBOX   at base + 0x8800   (paired u64 write: lo then hi)
#   OUTBOX  at base + 0x8830   (paired u64 read)
#   DOORBELL_BASE  base + 0x1004: write 0x10
#                  base + 0x1014: write 0x1
#   CPU_CONTROL    base + 0x0044  (RUN bit at 0x10)
#   RVBAR_LO       base + 0x1050
#
# The MTP ADT compatible is `iop,ascwrap-v6`; its reg[0] is the base
# address this script operates on.
import os, pathlib, sys, time
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2]
                       / "external" / "m1n1" / "proxyclient"))
from m1n1.proxy import M1N1Proxy, UartInterface
from m1n1.proxyutils import ProxyUtils, bootstrap_port

iface = UartInterface()
p = M1N1Proxy(iface, debug=False)
bootstrap_port(iface, p)
u = ProxyUtils(p, heap_size=16 * 1024 * 1024)

MTP_BASE, MTP_SIZE = u.adt["/arm-io/mtp"].get_reg(0)
print(f"MTP base 0x{MTP_BASE:x} size 0x{MTP_SIZE:x}")

INBOX   = MTP_BASE + 0x8800
OUTBOX  = MTP_BASE + 0x8830
DOORBELL_A = MTP_BASE + 0x1004
DOORBELL_B = MTP_BASE + 0x1014
CPU_CTRL   = MTP_BASE + 0x0044
RVBAR_LO   = MTP_BASE + 0x1050

def inbox_write(lo, hi):
    p.write64(INBOX, lo)
    p.write64(INBOX + 8, hi)

def outbox_read():
    return (p.read64(OUTBOX), p.read64(OUTBOX + 8))

def doorbell():
    p.write32(DOORBELL_A, 0x10)
    p.write32(DOORBELL_B, 0x1)

def run_cpu(enable):
    cur = p.read32(CPU_CTRL)
    if enable:
        p.write32(CPU_CTRL, cur | 0x10)
    else:
        p.write32(CPU_CTRL, cur & ~0x10)

def set_rvbar(rvbar):
    p.write64(RVBAR_LO, rvbar)

def expect_outbox(lo, hi, timeout_ms=1000):
    """Poll OUTBOX until it matches the captured value or timeout."""
    deadline = time.monotonic() + timeout_ms / 1000.0
    while time.monotonic() < deadline:
        got_lo, got_hi = outbox_read()
        if got_lo == lo and got_hi == hi:
            print(f"  OUTBOX match 0x{lo:016x} 0x{hi:016x}")
            return True
        time.sleep(0.01)
    print(f"  TIMEOUT waiting for OUTBOX 0x{lo:016x} 0x{hi:016x}; last="
          f"0x{got_lo:016x} 0x{got_hi:016x}")
    return False

'''

def emit_replay(events: List[Event]) -> str:
    """Produce a Python replay from the parsed event stream."""
    lines = [REPLAY_HEADER]
    for ev in events:
        if ev.kind == "inbox":
            lo = ev.args["lo"]
            hi = ev.args["hi"]
            lines.append(f"print('[{ev.ts}] inbox 0x{lo:016x} 0x{hi:016x}')")
            lines.append(f"inbox_write(0x{lo:016x}, 0x{hi:016x})")
        elif ev.kind == "outbox":
            lo = ev.args["lo"]
            hi = ev.args["hi"]
            lines.append(f"print('[{ev.ts}] expect outbox 0x{lo:016x} 0x{hi:016x}')")
            lines.append(f"expect_outbox(0x{lo:016x}, 0x{hi:016x})")
        elif ev.kind == "doorbell":
            lines.append(f"print('[{ev.ts}] doorbell')")
            lines.append("doorbell()")
        elif ev.kind == "runCPU":
            en = ev.args["enable"]
            lines.append(f"print('[{ev.ts}] runCPU({en})')")
            lines.append(f"run_cpu({en})")
        elif ev.kind == "setRVBAR":
            rv = ev.args["rvbar"]
            lines.append(f"print('[{ev.ts}] setRVBAR(0x{rv:x})')")
            lines.append(f"set_rvbar(0x{rv:x})")
        elif ev.kind == "mapFirmware":
            addr = ev.args["addr"]
            lines.append(f"print('[{ev.ts}] NOTE: macOS mapped firmware at 0x{addr:x}')")
            lines.append("# firmware staging — already handled by boot_mtp_dartmap.py")
        elif ev.kind in ("enableOutbox", "enableInboxIRQ", "enableOutboxIRQ",
                         "disableAllIRQ", "generateNMI", "ext_doorbell",
                         "start", "startCPU"):
            a = ", ".join(f"{k}={v}" for k, v in ev.args.items())
            lines.append(f"print('[{ev.ts}] NOTE: {ev.kind} {a}')")
            lines.append(f"# TODO: map {ev.kind} to the right MMIO primitive")
        lines.append("")
    lines.append("print('replay done')")
    return "\n".join(lines)


# --- main ------------------------------------------------------------

def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("trace", type=pathlib.Path,
                    help="dtrace output from trace_mtp_mailbox.d")
    ap.add_argument("--json", action="store_true",
                    help="dump parsed events as JSON instead of replay")
    args = ap.parse_args(argv)

    events: List[Event] = []
    for line in args.trace.open():
        ev = parse_line(line)
        if ev is not None:
            events.append(ev)

    events.sort(key=lambda e: e.ts)

    if args.json:
        import json
        print(json.dumps(
            [{"ts": e.ts, "kind": e.kind, "args": e.args} for e in events],
            indent=2))
        return 0

    sys.stdout.write(emit_replay(events))
    return 0


if __name__ == "__main__":
    sys.exit(main())
