#!/usr/bin/env python3
"""Audit ``captures/`` and report — DO NOT DELETE.

The repo carries ~7800 PNGs / ~2.4 GB in ``captures/`` from the
browser-era visual debugging work. Per the post-no-browser pivot
roadmap, this tree is now noise — but mass-deletion is the user's
call, so this script's job is just to *describe* what's there in
enough detail that a human (or a follow-up commit) can decide.

Output:
  * ``docs/CAPTURES_AUDIT.md`` — Markdown summary, safe to commit.
  * ``docs/captures_audit_full.tsv`` — full per-file TSV (filename,
    bytes, mtime, prefix-group, mod-date) for grep / spreadsheet use.

Both files go under ``docs/`` so they survive the eventual cleanup
even if ``captures/`` itself disappears.

Run:
    python3 scripts/audit_captures.py

This script is read-only over ``captures/``. Nothing is renamed,
moved, or deleted. The companion ``cleanup_captures.sh`` (TBD) will
take a flag picked from this audit's output and do the actual deletion
behind a confirmation prompt.
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path

REPO = Path("/Users/kadenlee/Sphragis")
CAPTURES = REPO / "captures"
OUT_MD  = REPO / "docs" / "CAPTURES_AUDIT.md"
OUT_TSV = REPO / "docs" / "captures_audit_full.tsv"

# Pattern: a 4-char prefix (e.g. "A001", "SV02", "z140") + extension.
# We bucket by the alphabetic chunk that comes before the digits, since
# that's what survived from the original test-run naming convention.
PREFIX_RE = re.compile(r'^([A-Za-z]+)\d')


def human_size(n: int) -> str:
    for unit in ("B", "KiB", "MiB", "GiB"):
        if n < 1024 or unit == "GiB":
            return f"{n:.1f} {unit}"
        n /= 1024
    return f"{n:.1f} GiB"


def main() -> int:
    if not CAPTURES.exists():
        print(f"[audit-captures] no captures/ at {CAPTURES} — nothing to audit", file=sys.stderr)
        return 0

    files = sorted([p for p in CAPTURES.iterdir() if p.is_file()])
    total_n = len(files)
    total_b = sum(p.stat().st_size for p in files)

    # Bucket by alphabetic prefix and by mtime month
    by_prefix: defaultdict[str, list[Path]] = defaultdict(list)
    by_month:  defaultdict[str, list[Path]] = defaultdict(list)
    by_size:   list[tuple[int, Path]] = []

    for p in files:
        m = PREFIX_RE.match(p.name)
        prefix = m.group(1) if m else "<other>"
        by_prefix[prefix].append(p)

        st = p.stat()
        mt = datetime.fromtimestamp(st.st_mtime, tz=timezone.utc)
        by_month[mt.strftime("%Y-%m")].append(p)
        by_size.append((st.st_size, p))

    by_size.sort(reverse=True)

    # Try to attribute via git: who first added captures/?
    git_intro = None
    try:
        r = subprocess.run(
            ["git", "log", "--diff-filter=A", "--format=%cs|%h %s",
             "--", "captures"],
            cwd=REPO, capture_output=True, text=True, timeout=10,
        )
        if r.returncode == 0 and r.stdout.strip():
            # Last line of git log = oldest add commit
            git_intro = r.stdout.strip().splitlines()[-1]
    except Exception:
        pass

    # Last commit that touched captures/
    git_last = None
    try:
        r = subprocess.run(
            ["git", "log", "-1", "--format=%cs|%h %s", "--", "captures"],
            cwd=REPO, capture_output=True, text=True, timeout=10,
        )
        if r.returncode == 0 and r.stdout.strip():
            git_last = r.stdout.strip()
    except Exception:
        pass

    # Render Markdown summary
    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    with OUT_MD.open("w", encoding="utf-8") as f:
        f.write("# `captures/` audit\n\n")
        f.write(
            f"_Generated by `scripts/audit_captures.py` at "
            f"{datetime.now(timezone.utc).isoformat()}._ "
            "**Read-only audit. Nothing deleted.**\n\n"
        )

        f.write("## Headline\n\n")
        f.write(f"- **{total_n:,} files** in `captures/`\n")
        f.write(f"- **{human_size(total_b)}** on disk\n")
        if git_intro:
            f.write(f"- First introduced: `{git_intro}`\n")
        if git_last:
            f.write(f"- Last touched:     `{git_last}`\n")
        f.write("\n")

        f.write("## Why this exists\n\n")
        f.write(
            "These PNGs were captured during the browser-era visual debugging "
            "work — page renders, framebuffer dumps, comparison shots. After "
            "the no-browser pivot (2026-05-08; see `[[Post-no-browser Pivot]]` "
            "in the vault, or `DESIGN_NO_BROWSER.md`), they are noise: not "
            "referenced by any current code path, not linked from any test, "
            "not part of any documentation. They are kept only because mass "
            "deletion of 2.4 GB needs a deliberate decision, not a sweep.\n\n"
        )

        f.write("## By prefix group (likely test-run buckets)\n\n")
        f.write("Each prefix was a separate browser test run. Sorted by file count.\n\n")
        f.write("| Prefix | Files | Total size |\n")
        f.write("|--------|-------|------------|\n")
        for prefix, plist in sorted(by_prefix.items(), key=lambda kv: -len(kv[1])):
            sz = sum(p.stat().st_size for p in plist)
            f.write(f"| `{prefix}` | {len(plist):,} | {human_size(sz)} |\n")
        f.write("\n")

        f.write("## By month (mtime)\n\n")
        f.write("| Month | Files | Total size |\n")
        f.write("|-------|-------|------------|\n")
        for month in sorted(by_month.keys()):
            plist = by_month[month]
            sz = sum(p.stat().st_size for p in plist)
            f.write(f"| {month} | {len(plist):,} | {human_size(sz)} |\n")
        f.write("\n")

        f.write("## Top 20 largest files\n\n")
        f.write("| Size | File |\n")
        f.write("|------|------|\n")
        for sz, p in by_size[:20]:
            f.write(f"| {human_size(sz)} | `{p.name}` |\n")
        f.write("\n")

        f.write("## Recommended deletion plan\n\n")
        f.write(
            "Two paths, each safe to take after a `git status` confirms a clean "
            "tree (so we can revert via `git restore` if anything goes wrong):\n\n"
        )
        f.write(
            "**Option A — full nuke** (recommended). One commit, remove the entire\n"
            "`captures/` tree, add a tombstone note in `docs/`.\n\n"
            "```sh\n"
            "git rm -r captures/\n"
            "echo 'captures/' >> .gitignore  # if not already\n"
            "git add docs/CAPTURES_AUDIT.md   # this report stays\n"
            "git commit -m 'cleanup: remove browser-era captures/ — see docs/CAPTURES_AUDIT.md'\n"
            "```\n\n"
        )
        f.write(
            "**Option B — selective archive**. Keep one prefix group as a "
            "representative sample (recommended: the smallest one), nuke the rest.\n\n"
            "```sh\n"
            "# Pick a small bucket to keep as a sample (say `A`, ~149 files):\n"
            "find captures/ -type f -not -name 'A*.png' -delete\n"
            "git add -u\n"
            "git commit -m 'cleanup: archive captures/ to A* sample only'\n"
            "```\n\n"
        )
        f.write(
            "Either way, the full per-file inventory at "
            "`docs/captures_audit_full.tsv` survives the cleanup so the deleted "
            "names are still searchable.\n"
        )

    # Render full TSV
    with OUT_TSV.open("w", encoding="utf-8") as f:
        f.write("filename\tbytes\tmtime_iso\tprefix\n")
        for p in files:
            st = p.stat()
            m = PREFIX_RE.match(p.name)
            prefix = m.group(1) if m else "<other>"
            mt = datetime.fromtimestamp(st.st_mtime, tz=timezone.utc).isoformat()
            f.write(f"{p.name}\t{st.st_size}\t{mt}\t{prefix}\n")

    print(f"[audit-captures] {total_n:,} files / {human_size(total_b)}")
    print(f"[audit-captures] wrote {OUT_MD.relative_to(REPO)}")
    print(f"[audit-captures] wrote {OUT_TSV.relative_to(REPO)}")
    print(f"[audit-captures] no files in captures/ were touched.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
