#!/usr/bin/env python3
"""Build the RAG corpus consumed by both the Python eval harness and
the kernel-side Rust agent.

Sources:
  * ~/SPHRAGIS_VAULT/Concepts/*.md    — hand-written editorial notes
  * DESIGN_*.md (repo root)         — top-level architecture docs

Outputs:
  * docs/rag_corpus/<slug>.md   — slugified, deterministic filenames so
    we can `include_str!` them from Rust without surprises
  * docs/rag_corpus/INDEX.json  — title -> path, body length, source

Run after editing any Concept note or DESIGN doc:
  python3 scripts/build_rag_corpus.py
"""
from __future__ import annotations

import json
import math
import re
import shutil
from pathlib import Path

REPO     = Path(__file__).resolve().parent.parent
VAULT    = Path.home() / "SPHRAGIS_VAULT"
OUT      = REPO / "docs" / "rag_corpus"
RUST_OUT = REPO / "src" / "ai" / "rag_corpus.rs"

TOKEN_RE = re.compile(r"[A-Za-z0-9_]+")


def tokenize(text: str) -> list[str]:
    return [m.group(0).lower() for m in TOKEN_RE.finditer(text)]


def fnv1a64(s: str) -> int:
    """Stable 64-bit hash so the Rust side reproduces the Python side."""
    h = 0xcbf29ce484222325
    for b in s.encode("utf-8"):
        h ^= b
        h = (h * 0x100000001b3) & 0xffffffffffffffff
    return h


def slugify(name: str) -> str:
    """`Audit Ring Contract.md` -> `audit_ring_contract`."""
    stem = name.removesuffix(".md")
    s = re.sub(r"[^A-Za-z0-9]+", "_", stem).strip("_").lower()
    return s or "untitled"


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    # Wipe stale slugs so a renamed source doesn't leave a duplicate.
    for old in OUT.glob("*.md"):
        old.unlink()

    index: list[dict] = []

    concepts_dir = VAULT / "Concepts"
    if concepts_dir.exists():
        for p in sorted(concepts_dir.glob("*.md")):
            slug = slugify(p.name)
            body = p.read_text(encoding="utf-8")
            out = OUT / f"concept_{slug}.md"
            out.write_text(body, encoding="utf-8")
            index.append({
                "slug": f"concept_{slug}",
                "title": p.stem,
                "kind": "concept",
                "source": str(p.relative_to(Path.home())),
                "bytes": len(body),
            })

    for p in sorted(REPO.glob("DESIGN_*.md")):
        slug = slugify(p.name)
        body = p.read_text(encoding="utf-8")
        out = OUT / f"design_{slug}.md"
        out.write_text(body, encoding="utf-8")
        index.append({
            "slug": f"design_{slug}",
            "title": p.stem,
            "kind": "design",
            "source": str(p.relative_to(REPO)),
            "bytes": len(body),
        })

    index_path = OUT / "INDEX.json"
    index_path.write_text(json.dumps(index, indent=2), encoding="utf-8")

    # ---- emit src/ai/rag_corpus.rs ---------------------------------
    # Precompute IDF for every term so the no_std runtime doesn't need
    # a logarithm. Sort the table by hash so the Rust side can binary
    # search. Tokenization here must match `tokenize` in evals/rag.py
    # and the runtime tokenizer in src/ai/rag.rs.
    doc_token_counts: list[int] = []
    df_counts: dict[str, int] = {}
    for entry in index:
        body = (OUT / f"{entry['slug']}.md").read_text(encoding="utf-8")
        toks = tokenize(body)
        doc_token_counts.append(len(toks))
        for t in set(toks):
            df_counts[t] = df_counts.get(t, 0) + 1
    n_docs = len(index)
    avg_doc_len = sum(doc_token_counts) / n_docs if n_docs else 0.0

    # Robertson-Sparck-Jones BM25 IDF.
    idf_table: list[tuple[int, float]] = []
    for term, df in df_counts.items():
        idf = math.log(1.0 + (n_docs - df + 0.5) / (df + 0.5))
        if idf > 0:
            idf_table.append((fnv1a64(term), idf))
    idf_table.sort(key=lambda x: x[0])

    rust = ["//! AUTO-GENERATED by scripts/build_rag_corpus.py — do not edit.",
            "//!",
            "//! Compile-time-bundled corpus + precomputed BM25 IDF table.",
            "//! Rebuild with `python3 scripts/build_rag_corpus.py` after any",
            "//! edit to Concept notes or DESIGN_*.md.",
            "",
            "use super::rag::CorpusEntry;",
            "",
            f"pub const CORPUS: &[CorpusEntry] = &["]
    for e in index:
        rel = f"../../docs/rag_corpus/{e['slug']}.md"
        rust.append(f"    CorpusEntry {{")
        # Escape any double-quote in title (none of ours have one, but be safe).
        title_escaped = e['title'].replace('\\', '\\\\').replace('"', '\\"')
        rust.append(f"        title: \"{title_escaped}\",")
        rust.append(f"        body: include_str!(\"{rel}\"),")
        rust.append(f"    }},")
    rust.append("];")
    rust.append("")
    rust.append(f"pub const DOC_TOKEN_COUNTS: &[u32] = &{doc_token_counts!r};".replace("[", "[").replace("]", "]"))
    rust.append("")
    rust.append(f"pub const AVG_DOC_LEN: f32 = {avg_doc_len:.6};")
    rust.append("")
    rust.append(f"/// Sorted by hash so callers can binary search. {len(idf_table)} entries.")
    rust.append("pub const IDF_TABLE: &[(u64, f32)] = &[")
    for h, idf in idf_table:
        rust.append(f"    (0x{h:016x}, {idf:.6}),")
    rust.append("];")
    rust.append("")

    RUST_OUT.write_text("\n".join(rust), encoding="utf-8")

    total_bytes = sum(e["bytes"] for e in index)
    print(f"[rag-corpus] {len(index)} entries, {total_bytes:,} bytes -> {OUT.relative_to(REPO)}/")
    for e in index:
        print(f"  {e['slug']:<40} {e['bytes']:>7} B  {e['title']}")
    print(f"[rag-corpus] {len(idf_table)} IDF entries, avg_doc_len={avg_doc_len:.1f}")
    print(f"[rag-corpus] wrote {RUST_OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
