#!/usr/bin/env python3
"""
Pre-render Σ at 96px from IBM Plex Serif Italic using PIL's high-quality
font renderer, export as a Rust `const [u8; 96*96]` alpha bitmap.

PIL gives us correct outline iteration + proper anti-aliasing that the
kernel's truetype.rs rasterizer can't yet match. Baked at build time, the
kernel just blits the bitmap — no rasterizer touched.

Re-run if the font or size changes:
  python3 scripts/gen_sigma_bitmap.py
"""
from __future__ import annotations

from pathlib import Path
from PIL import Image, ImageDraw, ImageFilter, ImageFont

ROOT = Path(__file__).resolve().parent.parent
FONT_PATH = ROOT / "fonts" / "ibm-plex-serif-italic.ttf"
OUT_PATH = ROOT / "src" / "ui" / "sigma_bitmap.rs"
SIZE = 96
GLYPH = "Σ"


def main() -> None:
    if not FONT_PATH.exists():
        raise SystemExit(f"font not found: {FONT_PATH}")

    # Render Σ at a larger nominal point size, then crop to bounds. Plex
    # Serif Italic at "size=96" rasterizes with comfortable padding above
    # the cap height; we crop so the resulting bitmap is exactly 96×96
    # with the glyph filling it (a few pixels of bottom padding for the
    # baseline is fine — we treat the bitmap as one rectangular block).
    # Render at 8× internal resolution (768 px), apply a tiny Gaussian
    # blur to smooth FreeType edge artifacts, then LANCZOS-downsample
    # to 96×96. 8× supersampling gives 64 sub-samples per output pixel
    # — way more than enough for the diagonal-and-curved strokes Σ has,
    # and the pre-downsample blur softens the harshest pixel-edge
    # transitions on the strokes.
    super_factor = 8
    super_size = SIZE * super_factor
    super_font = ImageFont.truetype(str(FONT_PATH), super_size)
    super_img = Image.new("L", (super_size * 4, super_size * 2), 0)
    draw = ImageDraw.Draw(super_img)
    draw.text((super_factor * 4, super_factor * 4), GLYPH, font=super_font, fill=255)
    bbox = super_img.getbbox()
    if bbox is None:
        raise SystemExit("PIL produced an empty Σ bitmap — font lookup failed?")
    cropped = super_img.crop(bbox)
    # Soften with a small Gaussian relative to the supersample factor.
    # Radius ~= super_factor / 4 gives a half-pixel blur in the final
    # 96×96 output — enough to take the harsh stair-step edges off the
    # diagonals without softening the glyph itself.
    cropped = cropped.filter(ImageFilter.GaussianBlur(radius=super_factor / 4.0))
    cw, ch = cropped.size
    side = max(cw, ch)
    square = Image.new("L", (side, side), 0)
    square.paste(cropped, ((side - cw) // 2, (side - ch) // 2))
    final = square.resize((SIZE, SIZE), Image.LANCZOS)

    pixels = list(final.getdata())
    assert len(pixels) == SIZE * SIZE, f"got {len(pixels)} pixels, expected {SIZE*SIZE}"

    # Emit Rust source. 16 bytes per row in the array for readability.
    lines = [
        "// Auto-generated by scripts/gen_sigma_bitmap.py — do not edit by hand.",
        "// 96×96 alpha bitmap of Σ rendered from IBM Plex Serif Italic via PIL,",
        "// then downsampled 2×→1× for cleaner anti-aliasing than our in-kernel",
        "// rasterizer can currently produce. Re-run the script if you change",
        "// the font, size, or want a different glyph variant.",
        "",
        "#![allow(dead_code)]",
        "",
        f"pub const SIGMA_BITMAP_W: u32 = {SIZE};",
        f"pub const SIGMA_BITMAP_H: u32 = {SIZE};",
        "",
        f"pub static SIGMA_BITMAP_96: [u8; {SIZE} * {SIZE}] = [",
    ]
    bytes_per_line = 16
    for row in range(SIZE):
        for col_chunk in range(0, SIZE, bytes_per_line):
            chunk = pixels[row * SIZE + col_chunk : row * SIZE + col_chunk + bytes_per_line]
            lines.append("    " + " ".join(f"0x{b:02X}," for b in chunk))
    lines.append("];")
    lines.append("")

    OUT_PATH.write_text("\n".join(lines))
    print(f"wrote {OUT_PATH} ({OUT_PATH.stat().st_size} bytes, "
          f"{SIZE}×{SIZE} alpha bitmap)")


if __name__ == "__main__":
    main()
