/*
 * Sphragis — testament.h for NetSurf
 * Build-time metadata; generated by NetSurf's build system.
 */
#ifndef _SPHRAGIS_TESTAMENT_H
#define _SPHRAGIS_TESTAMENT_H

#define WT_COMPILERFLAGS ""
#define WT_COMPILER      "clang (Sphragis cross)"
#define WT_HOSTNAME      "sphragis"
#define WT_ROOT          "/netsurf"
#define WT_USERNAME      "sphragis"
#define WT_BRANCHPATH    "master"

#define WT_CI_BUILD      0

#define WT_MODIFICATIONS "clean"
#define WT_BRANCHISTRUNK 1
#endif /* _SPHRAGIS_TESTAMENT_H */
