/*
 * Bat_OS — testament.h for NetSurf
 * Build-time metadata; generated by NetSurf's build system.
 */
#ifndef _BATOS_TESTAMENT_H
#define _BATOS_TESTAMENT_H

#define WT_COMPILERFLAGS ""
#define WT_COMPILER      "clang (Bat_OS cross)"
#define WT_HOSTNAME      "batos"
#define WT_ROOT          "/netsurf"
#define WT_USERNAME      "batos"
#define WT_BRANCHPATH    "master"

#define WT_CI_BUILD      0

#define WT_MODIFICATIONS "clean"
#define WT_BRANCHISTRUNK 1
#endif /* _BATOS_TESTAMENT_H */
